@startuml

title 科研课题动态管理系统架构

科研课题动态管理系统 -d-> 个人管理
	个人管理 -d-> 个人信息
		个人信息 -d-> 修改信息
	个人管理 -d-> 修改密码
科研课题动态管理系统 -d-> 课题管理
	课题管理 -d-> 课题申报
	课题管理 -d-> 显示课题
		显示课题 -d-> 修改课题
	课题管理 -d-> 更新进度
	课题管理 -d-> 结题申请
科研课题动态管理系统 -d-> 系统管理
	系统管理 -d-> 用户管理
	系统管理 -d-> 权限管理

@enduml